CREATE TABLE EMPLOYEE (
	E_ID VARCHAR(5) PRIMARY KEY,
	E_Name VARCHAR(20),
	E_Role VARCHAR(20),
	E_Phone INT(10)
);

INSERT INTO EMPLOYEE (E_ID, E_Name, E_Role, E_Phone) VALUES('E2', 'Fawaz Abid', 'GOD', 8904751906);

ALTER TABLE EMPLOYEE MODIFY E_PHONE BIGINT(10)

CREATE TABLE SUPPLIER (
	S_ID VARCHAR(5) PRIMARY KEY,
	S_Name VARCHAR(20),
	S_Phone BIGINT(10),
	S_Email VARCHAR(20),
	E_ID VARCHAR(5)  REFERENCES EMPLOYEE(E_ID) ON DELETE CASCADE

);

CREATE TABLE RETAILER (
	R_ID VARCHAR(5) PRIMARY KEY,
	R_Name VARCHAR(20),
	R_Phone BIGINT(10),
	R_Email VARCHAR(20),
	Loc VARCHAR(20),
	E_ID VARCHAR(5)  REFERENCES EMPLOYEE(E_ID) ON DELETE CASCADE

);

CREATE TABLE ORDERS (
	O_ID VARCHAR(5) PRIMARY KEY,
	Cost FLOAT(10),
	Ord_date DATE,
	Rcv_date DATE,
	S_ID VARCHAR(5),  
	R_ID VARCHAR(5),
	FOREIGN KEY (S_ID)  REFERENCES SUPPLIER(S_ID) ON DELETE CASCADE,
	FOREIGN KEY (R_ID)  REFERENCES RETAILER(R_ID) ON DELETE CASCADE
);

CREATE TABLE ITEMS (
	I_ID INT AUTO_INCREMENT PRIMARY KEY,
	I_Name VARCHAR(20),
	Price FLOAT(10),
	Quantity INT(10),
	O_ID VARCHAR(5), 
	FOREIGN KEY(O_ID) REFERENCES ORDERS(O_ID) ON DELETE CASCADE
);

ALTER TABLE EMPLOYEE ADD password varchar;

CREATE TABLE ITEMS_ORDERED (
	I_ID VARCHAR(5),
	O_ID VARCHAR(5),
	Quantity INT(10),
	FOREIGN KEY (I_ID)  REFERENCES ITEMS(I_ID) ON DELETE CASCADE,
	FOREIGN KEY (O_ID)  REFERENCES ORDERS(O_ID) ON DELETE CASCADE
);


INSERT INTO `distributor`.`employee`
(`E_ID`,
`E_Name`,
`E_Role`,
`E_Phone`,
`password`)
VALUES
(2,
'vin',
'manager',
11212111,
'123123');
INSERT INTO `distributor`.`supplier`
(`S_ID`,
`S_Name`,
`S_Phone`,
`S_Email`,
`E_ID`)
VALUES
(1,
'FAW',
1111111,
'sdfsafd',
2);


INSERT INTO `distributor`.`retailer`
(`R_ID`,
`R_Name`,
`R_Phone`,
`R_Email`,
`Loc`,
`E_ID`)
VALUES
(3,
'abhi',
3231231,
'gfbdavd',
'dabradb',
2);










INSERT INTO `distributor`.`orders`
(`O_ID`,
`Cost`,
`Ord_date`,
`Rcv_date`,
`S_ID`,
`R_ID`)
VALUES
(1,
20,
'2022-01-01' ,
'2022-01-01',
1,
3);


INSERT INTO `distributor`.`items`
(
`I_Name`,
`Price`,
`Quantity`,
`O_ID`)
VALUES
(
'Faw',
50 ,
10 ,
1 );


INSERT INTO `distributor`.`orders`
(`O_ID`,

`Ord_date`,
`Rcv_date`,
`S_ID`
)
VALUES
(3,

curdate() ,
'2022-01-01',
1
);
