CREATE TABLE EMPLOYEE (
	E_ID VARCHAR(5) PRIMARY KEY,
	E_Name VARCHAR(20),
	E_Role VARCHAR(20),
	E_Phone INT(10)
);

INSERT INTO EMPLOYEE (E_ID, E_Name, E_Role, E_Phone) VALUES('E2', 'Fawaz Abid', 'GOD', 8904751906);

ALTER TABLE EMPLOYEE MODIFY E_PHONE BIGINT(10)

CREATE TABLE SUPPLIER (
	S_ID VARCHAR(5) PRIMARY KEY,
	S_Name VARCHAR(20),
	S_Phone BIGINT(10),
	S_Email VARCHAR(20),
	E_ID VARCHAR(5) FOREIGN KEY REFERENCES EMPLOYEE(E_ID) ON DELETE CASCADE

);

CREATE TABLE RETAILER (
	R_ID VARCHAR(5) PRIMARY KEY,
	R_Name VARCHAR(20),
	R_Phone BIGINT(10),
	R_Email VARCHAR(20),
	Loc VARCHAR(20),
	E_ID VARCHAR(5) FOREIGN KEY REFERENCES EMPLOYEE(E_ID) ON DELETE CASCADE

);

CREATE TABLE ORDER (
	O_ID VARCHAR(5) PRIMARY KEY,
	Cost FLOAT(10),
	Ord_date DATE,
	Rcv_date DATE,
	S_ID VARCHAR(5) FOREIGN KEY REFERENCES SUPPLIER(S_ID) ON DELETE CASCADE
	R_ID VARCHAR(5) FOREIGN KEY REFERENCES RETAILER(R_ID) ON DELETE CASCADE
);

CREATE TABLE ITEMS (
	I_ID VARCHAR(5) PRIMARY KEY,
	I_Name VARCHAR(20),
	Price FLOAT(10),
	Quantity INT(10),
	O_ID VARCHAR(5) FOREIGN KEY REFERENCES ORDER(O_ID) ON DELETE CASCADE
);